version: 2.1

jobs:
  release-pr:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: npm ci
      - run: |
          npx release-please release-pr \
            --token $GITHUB_TOKEN \
            --repo-url $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
            --target-branch $CIRCLE_BRANCH \
            --config-file .circleci/release/release-please-config.json \
            --manifest-file .circleci/release/release-please-manifest.json

  github-release:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: npm ci
      - run: |
          npx release-please github-release \
            --token $GITHUB_TOKEN \
            --repo-url $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
            --target-branch $CIRCLE_BRANCH \
            --config-file .circleci/release/release-please-config.json \
            --manifest-file .circleci/release/release-please-manifest.json

  lint-pr:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Install GitHub CLI
          command: |
            curl -OL https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_amd64.deb
            sudo dpkg -i gh_2.32.1_linux_amd64.deb
      - run:
          name: Lint PR title
          command: gh pr view --json title --jq .title | npx commitlint

  auto-assign-pr:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Install GitHub CLI
          command: |
            curl -OL https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_amd64.deb
            sudo dpkg -i gh_2.32.1_linux_amd64.deb
      - run:
          name: Assign PR to author
          command: gh pr view --json author --jq .author.login | xargs gh pr edit --add-assignee

workflows:
  Lint-test-build:
    jobs:
      - lint-pr:
          filters:
            branches:
              ignore:
                - main
                - /hotfix.*/
      - auto-assign-pr:
          filters:
            branches:
              ignore:
                - main
                - /hotfix.*/

  Prepare release:
    jobs:
      - release-pr:
          name: Create or update release PR
          filters:
            branches:
              only:
                - main
                - /hotfix.*/
  GitHub release:
    jobs:
      - github-release:
          name: Create github release
          filters:
            branches:
              only:
                - main
                - /hotfix.*/
